import {
 FaGraduationCap,
 FaBriefcase,
 FaBookOpen,
 FaServer,
 FaCloud,
 FaDatabase,
 FaGithub,
 FaHtml5,
 FaCss3Alt,
 FaJava,
 FaGitAlt,
 FaJsSquare,
 FaNodeJs,
 FaBootstrap,
 FaReact,
 FaCpanel,
 FaAppStoreIos,
 FaGooglePlay,
 FaTools,
 FaLaptopCode,
 FaLayerGroup,
 FaSearch,
 FaStore,
} from "react-icons/fa";

import {
 SiAutodesk,
 SiNextdotjs,
 SiMongodb,
 SiTypescript,
 SiTailwindcss,
 SiExpress,
 SiAutocad,
 SiPostgresql,
 SiPrisma,
 SiMysql,
 SiVercel,
 SiPostman,
 SiRedux,
 SiGooglegemini,
 SiShadcnui,
 SiNextui,
 SiChakraui,
 SiHeadlessui,
 SiRadixui,
 SiGooglemaps,
 SiGoogleanalytics,
 SiGooglesearchconsole,
 SiFlutter,
 SiAndroidstudio,
 SiExpo,
 SiRailway,
 SiRender,
 SiJavascript,
} from "react-icons/si";

import { MdElectricBolt, MdDomain } from "react-icons/md";
import { FcElectronics } from "react-icons/fc";
import { BsCursorFill } from "react-icons/bs";
import { DiVisualstudio } from "react-icons/di";
import { GrCertificate } from "react-icons/gr";
import { TbApi, TbBrandReactNative, TbSeo, TbSql } from "react-icons/tb";
import { RxMobile } from "react-icons/rx";
import IxirhostIcon from "./IxirhostIcon";

export const ICON_MAP = {
 FaGraduationCap,
 FaBriefcase,
 FaBookOpen,
 FaServer,
 FaCloud,
 FaDatabase,
 FaGithub,
 FaHtml5,
 FaCss3Alt,
 FaJava,
 FaReact,
 FaGitAlt,
 FaJsSquare,
 FaNodeJs,
 FaBootstrap,
 FaCpanel,
 FaAppStoreIos,
 FaGooglePlay,
 FaTools,
 FaLaptopCode,
 FaLayerGroup,
 FaSearch,
 FaStore,
 SiAutodesk,
 SiNextdotjs,
 SiMongodb,
 SiTypescript,
 SiTailwindcss,
 SiExpress,
 SiAutocad,
 SiPostgresql,
 SiPrisma,
 SiMysql,
 SiVercel,
 MdElectricBolt,
 MdDomain,
 FcElectronics,
 BsCursorFill,
 DiVisualstudio,
 GrCertificate,
 TbApi,
 TbBrandReactNative,
 SiPostman,
 SiRedux,
 SiGooglegemini,
 SiShadcnui,
 SiNextui,
 SiChakraui,
 SiHeadlessui,
 SiRadixui,
 SiGooglemaps,
 SiGoogleanalytics,
 SiGooglesearchconsole,
 SiFlutter,
 SiAndroidstudio,
 SiExpo,
 SiRailway,
 SiRender,
 SiJavascript,
 IxirhostIcon,
 TbSeo,
 TbSql,
 RxMobile,
};

export const ICON_COLOR_MAP = {
 FaHtml5: "text-orange-600",
 FaCss3Alt: "text-blue-500",
 FaJsSquare: "text-yellow-400",
 FaReact: "text-cyan-400",
 FaNodeJs: "text-green-600",
 FaBootstrap: "text-purple-600",
 FaDatabase: "text-adaptive-icon",
 FaGithub: "text-adaptive-icon",
 FaGitAlt: "text-orange-600",
 FaCloud: "text-blue-400",
 FaServer: "text-adaptive-icon",
 FaJava: "text-red-600",
 FaCpanel: "text-orange-600",
 FaAppStoreIos: "text-adaptive-icon",
 FaGooglePlay: "text-green-500",
 FaTools: "text-amber-500",
 FaLaptopCode: "text-blue-400",
 FaLayerGroup: "text-teal-400",
 FaSearch: "text-green-500",
 FaStore: "text-indigo-400",
 FaGraduationCap: "text-green-400",
 FaBriefcase: "text-adaptive-icon",
 FaBookOpen: "text-adaptive-icon",
 GrCertificate: "text-adaptive-icon",

 SiNextdotjs: "text-adaptive-icon",
 SiTypescript: "text-blue-600",
 SiTailwindcss: "text-cyan-500",
 SiExpress: "text-adaptive-icon",
 SiMongodb: "text-green-500",
 SiMysql: "text-blue-600",
 SiPostgresql: "text-blue-600",
 SiPrisma: "text-indigo-600",
 SiVercel: "text-adaptive-icon",
 SiAutocad: "text-red-600",
 SiAutodesk: "text-blue-600",
 SiPostman: "text-orange-500",
 TbApi: "text-green-500",
 TbBrandReactNative: "text-cyan-400",
 IxirhostIcon: "",
 SiRedux: "text-purple-500",
 SiGooglegemini: "text-blue-400",
 SiShadcnui: "text-adaptive-icon",
 SiNextui: "text-adaptive-icon",
 SiChakraui: "text-teal-400",
 SiHeadlessui: "text-sky-400",
 SiRadixui: "text-adaptive-icon",
 SiGooglemaps: "text-red-500",
 SiGoogleanalytics: "text-orange-500",
 SiGooglesearchconsole: "text-blue-500",
 SiFlutter: "text-sky-400",
 SiAndroidstudio: "text-green-500",
 SiExpo: "text-adaptive-icon",
 SiRailway: "text-adaptive-icon",
 SiRender: "text-adaptive-icon",
 TbSeo: "text-emerald-500",
 TbSql: "text-slate-400",
 RxMobile: "text-cyan-400",
 SiJavascript: "text-yellow-400",

 FcElectronics: "text-blue-500",
 MdElectricBolt: "text-yellow-500",
 MdDomain: "text-purple-500",
 BsCursorFill: "text-adaptive-icon",
 DiVisualstudio: "text-blue-500",
};